run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
