# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test2

on:
  workflow_run:
    workflows: [Test1]
    types:
      - completed

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: LouisBrunner/checks-action@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: test k8s
          status: in_progress
          output: |
            {"summary": "",
            "title": "This check has started..."}